[workspace]
members = ["cldr_pluralrules_parser", "make_pluralrules", "intl_pluralrules", "i18next_parser_core", "i18next_parser" ]
resolver = "2"

[profile.dev]
opt-level = 0
debug = true
panic = "abort"

[profile.test]
opt-level = 0
debug = true
