name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout
        with:
          fetch-depth: 0
      - name: Git Version
        id: version
        uses: codacy/git-version@2.7.1
      - name: Bump version
        shell: bash
        run: sed -i -e 's/^version = .*/version = "${{ steps.version.outputs.version }}"/' i18next_parser*/Cargo.toml
      - name: Generate a changelog
        uses: orhun/git-cliff-action@v3
        id: i18next-parser
        with:
          config: cliff.toml
          args: --verbose --no-exec --tag ${{ steps.version.outputs.version }}
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}
      - name: Get last commit message
        id: last-commit
        run: |
          echo "message=$(git log -1 --pretty=%s)" >> $GITHUB_OUTPUT
          echo "author=$(git log -1 --pretty=\"%an <%ae>\")" >> $GITHUB_OUTPUT
      - name: Commit bump_version
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: master
          commit_author: ${{ steps.last-commit.outputs.author }}
          commit_message: "chore: bumped version to ${{ steps.version.outputs.version }}\n\nOld message: ${{ steps.last-commit.outputs.message }}"
          file_pattern: "CHANGELOG.md */Cargo.toml"
          tagging_message: ${{ steps.version.outputs.version }}
          commit_options: "--amend --no-edit"
          push_options: "--force-with-lease"
          skip_fetch: true
      - name: Trigger tag
        run: gh workflow run tag.yaml --ref ${{ steps.version.outputs.version }}
        env:
          GH_TOKEN: ${{ github.token }}
