name: Release

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Bump version
        uses: tj-actions/cargo-bump@v3
      # Commit and Push changes to the Cargo.toml
      - name: Release
        uses: softprops/action-gh-release@v2
